#!/bin/sh

source /etc/ltaDaemon.conf

#[ -f $CONFIG ] || exit 1
[ -x $DAEMONDIR/$DAEMON ] || exit 1

# Source function library.
. /etc/init.d/functions

case "$1" in
  start)
    echo -n "Starting ltaDaemon: "
    ( cd $DAEMONDIR && start-stop-daemon --start --quiet --background --make-pidfile --pidfile /var/run/ltaDaemon.pid --exec ./$DAEMON -- $DAEMONARGS )
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
        echo "OK"
    else
        echo "FAIL"
    fi
    ;;
  stop)
    echo -n "Stopping ltaDaemon: "
    start-stop-daemon --stop --quiet --background --make-pidfile --pidfile /var/run/ltaDaemon.pid
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
        echo "OK"
    else
        echo "FAIL"
    fi
    ;;
  status)
    status $DAEMON
    exit $?
    ;;
  restart)
    $0 stop && sleep 1 && $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/ltaDaemon {start|stop|status|restart}"
    exit 1
esac

exit 0

